trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'sonarcloud'
    organization: 'batch4devops'
    scannerMode: 'other'

- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1 (2dee7ddc-0ea0-42b8-bb8b-8e9cbf483738)'
    mavenPomFile: 'pom.xml'
    goals: 'verify package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudAnalyze@4
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'